#!/bin/sh

export PATH=/opt/gcc-arm-none-eabi/bin:$PATH

function run {
	make $1.bin && \
    	qemu-system-arm -M connex -pflash $1.bin -nographic -serial none
}

function debug {
	make $1.bin && \
    	qemu-system-arm -M connex -pflash $1.bin -nographic -serial none -s -S
}